### ISSUE TITLE
add BAR to rapid

### ISSUE THREAD

**Issue by Ruwetuin** [spring/RapidTools#65] opened 2019-06-02 11:09 UTC
https://github.com/beyond-all-reason/Beyond-All-Reason

(if bar already exists, then replace it with this repo?)

**Comment by abma** [comment] 2019-06-02 13:25
done!

**Comment by nixtux** [comment] 2019-06-02 16:43
Imo this should never have happened, its a different project they should use a new modshort etc for beyond all reason.

**Comment by silentwings** [comment] 2019-06-02 17:11
Yes - use a different shortname & rapid tag please (if you didn't already).

**Comment by nixtux** [comment] 2019-06-02 17:12
And rapid tag from BAR

**Comment by Ruwetuin** [comment] 2019-06-02 20:23
I dont see the issue here. Balanced Annihilation Reloaded/Remodeled isnt a thing anymore. Beyond all Reason is that... kind of. BA removed the remodeled units, and agreed to not let that be a thing. Beyond all Reason split of to be that.
The old repo isnt relevant anymore, hasnt been used in years too?

**Comment by silentwings** [comment] 2019-06-02 21:36
The Balanced Annihilation Reloaded repo was updated for the current major release (Spring 104, by me) and I may do it again for 105 one day. I own the https://github.com/balanced-annihilation-reloaded repo and I want it kept on rapid for now. Its rapid tags are currently not anyone else's to take.

The "new" incantation of BAR intentionally misses elements of the original project - some big ones are the Chili UI, all the missions/campaign, & BAs classic balance. https://github.com/beyond-all-reason is a new project, which was forked from the BA10 repo (not from BAR!) and uses the models via CC-BY-SA; it is not a continuation of the goals of the original BAR, and it does not preserve many of the assets.

I'm OK for you to use "bar" as a working title for your new project, but use e.g. "byar" as its shortname, and byar:stable and byar:rapid on rapid for https://github.com/beyond-all-reason, to keep the distinction within infra.

@abma I feel strongly about this, fix it please!

**Comment by ashdnazg** [comment] 2019-06-02 23:40
I agree with silentwings 100%

**Comment by Ruwetuin** [comment] 2019-06-03 13:46
okay then

**Comment by ashdnazg** [comment] 2019-06-03 13:54
@abma are the repos now separate?

**Comment by Ruwetuin** [comment] 2019-06-03 14:44
we'll use shortname BAR_

**Comment by nixtux** [comment] 2019-06-03 14:55
That won't be acceptable imo

**Comment by nixtux** [comment] 2019-06-03 15:02
As the issue is todo with name/branding please read https://springrts.com/wiki/Licenses_Forking_Mutators which I remember you asked for, especially this section Names, version numbers and other branding should not attempt to imitate the original game X;  which BAR_ does

**Comment by Fx-Doo** [comment] 2019-06-03 15:36
In this case, game Y doesn't attempt to imitate its original game "X", cause in this case game "X" is BA v10, and game "Y" would be Beyond All Reason. That rule doesn't state that it's impossible for 2 games to share a similar [names, version numbers and other branding] if they are unrelated to one another in terms of original-fork relationships. This rule doesn't apply here.

As far as I know, there is no "BAR_" game, the shortname is "free" to use, and Beyond All Reason differs from Balanced Annihilation, BAR_ differs from BA, and the versioning is entirely different.
As far as forking rules are concerned, BAR_ doesn't break any.

**Comment by ashdnazg** [comment] 2019-06-03 15:48
Please no lawyering, these are guidelines, not the word of god.
If BAR_ is ok with @silentwings (as the owner of the repo) I'm ok with it, otherwise I'm against it.

**Comment by Fx-Doo** [comment] 2019-06-03 16:07
Don't misunderstand me, i dislike nitpicking on rules. Just as much as I dislike attempts to manipulate/use rules in order to serve hidden personal interests instead of simply discussing the matter at hand as civilized people who can understand each other.

@ashdnazg you are also right, it's all down to Bluestone as he is the sole owner of the repo indeed. 
I would just argue with him that i wouldn't find it fair treatment to force unrelated games to comply with his demand to not use BAR as a short name (or names similar to BAR) when there is no development nor action taken to find devs for the "original" BAR game.

For lack of any knowledge on a serious project regarding BAR's future (beside just keeping the repo alive), I personally consider it as an unreleased vegetative project and believe that, while it should be safeguarded and kept alive as much as possible, it shouldn't become a limiter/brake to newer and active projects.

Of course, if despite that, he still wants to hold onto the BAR acronym/shortname, then there is nothing to be done beside finding another acronym.

**Comment by nixtux** [comment] 2019-06-03 18:06
Yeah let bluestone decide I don't want any thinking I have some ulterior motive. 

@fx-doo there not need to cast aspersions to try and make your view more favorable.

**Comment by silentwings** [comment] 2019-06-03 22:31
I've already made my views clear in https://github.com/spring/RapidTools/issues/65#issuecomment-498048748 and responded with the reasons in https://github.com/spring/RapidTools/issues/65#issuecomment-498067474

The idea that BAR and BAR are somehow not related to each other is just plain silly.

I don't care what Beyond All Reason has for its (new, as yet unoccupied) shortname/rapid tag, afaik these things are internal and never seen outside infra code. Fwiw picking "bar_" over "byar" or suchlike seems potentially childish, if so I guess it may be regretted in future, but that's not my concern. More practically, in the past it was necessary that shortnames did not contain whitespaces, # or _ (I guess/hope @abma knows if this is still required?).

I _do_ care that https://github.com/Balanced-Annihilation-Reloaded has its rapid tag returned.

Also, please avoid closing tickets that were re-opened by commiters.

**Comment by abma** [comment] 2019-06-04 06:22
so, two repos: byar and bar, right?

**Comment by silentwings** [comment] 2019-06-04 06:33
'bar' stays with https://github.com/Balanced-Annihilation-Reloaded, thanks

Floris or another owner of https://github.com/beyond-all-reason should choose a valid shortname/tag for their project ('byar' was only my suggestion, not sure if they want that or not).

**Comment by Ruwetuin** [comment] 2019-06-05 17:44
byar it is then

**Comment by abma** [comment] 2019-06-21 22:51
done!

**Closed as completed by abma** 2019-06-21 22:51 UTC
